apiVersion: v1
kind: Secret
metadata:
  name: postgres-creds
type: Opaque
stringData:
  POSTGRES_DB: products
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: pgs3cr3t
  database_uri: postgresql+psycopg://postgres:pgs3cr3t@postgres:5432/products
